// Generated by session-9-agent — 2026-03-09T00:00:00Z
// STUB: Threat Intel — full implementation planned for PD2
export default function ThreatIntelPage() {
  return (
    <main className="flex flex-col gap-4">
      <h1 className="text-2xl font-semibold tracking-tight">Threat Intel</h1>
      <div
        className="flex items-center justify-center rounded border border-dashed border-border py-24 text-muted-foreground"
        data-testid="coming-pd2"
      >
        Coming in PD2
      </div>
    </main>
  )
}
