// Generated by session-9-agent — 2026-03-09T00:00:00Z
'use client'

import { useMLHealth } from '@/features/ml-health/queries'
import type { ConfidenceThresholds } from '@/features/ml-health/types'

// TODO: MLHealthData does not yet include ECE, Brier score, OOD retention, Failover Mode,
// or model hash. Rendering available fields only. Extend the type when backend adds them.

function StatusBadge({ status }: { status: 'HEALTHY' | 'DEGRADED' | 'DOWN' }) {
  const colorMap: Record<'HEALTHY' | 'DEGRADED' | 'DOWN', string> = {
    HEALTHY: 'bg-green-100 text-green-800',
    DEGRADED: 'bg-yellow-100 text-yellow-800',
    DOWN: 'bg-red-100 text-red-800',
  }
  return (
    <span
      className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${colorMap[status]}`}
    >
      {status}
    </span>
  )
}

function MetricRow({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="flex items-center justify-between border-b border-border py-2 last:border-0">
      <span className="text-sm text-muted-foreground">{label}</span>
      <span className="text-sm font-medium">{value}</span>
    </div>
  )
}

function ThresholdsSection({ thresholds }: { thresholds: ConfidenceThresholds }) {
  return (
    <div className="rounded border border-border p-4">
      <h3 className="mb-2 text-sm font-semibold">Confidence Thresholds</h3>
      <MetricRow label="Low"    value={thresholds.low} />
      <MetricRow label="Medium" value={thresholds.medium} />
      <MetricRow label="High"   value={thresholds.high} />
    </div>
  )
}

export default function MLHealthDetail() {
  const { data, isPending, isError, error, refetch } = useMLHealth()

  if (isPending) {
    return (
      <div className="flex flex-col gap-3 animate-pulse" data-testid="ml-health-skeleton">
        <div className="h-6 w-40 rounded bg-muted" />
        <div className="h-4 w-24 rounded bg-muted" />
        <div className="h-32 w-full rounded bg-muted" />
      </div>
    )
  }

  if (isError) {
    return (
      <div
        className="flex flex-col items-center gap-4 rounded border border-destructive/50 bg-destructive/10 p-6"
        data-testid="ml-health-error"
      >
        <p className="text-sm font-medium text-destructive">
          Failed to load ML Health data
        </p>
        <p className="text-xs text-muted-foreground">
          {error instanceof Error ? error.message : 'Unknown error'}
        </p>
        <button
          onClick={() => void refetch()}
          className="rounded bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
        >
          Retry
        </button>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-6" data-testid="ml-health-detail">
      {/* Model Identity */}
      <div className="flex items-center gap-3">
        <div>
          <p className="text-xs text-muted-foreground">Model Version</p>
          <p className="font-mono text-sm font-semibold">{data.model_version}</p>
        </div>
        <StatusBadge status={data.status} />
      </div>

      {/* Core Metrics */}
      <div className="rounded border border-border p-4">
        <h3 className="mb-2 text-sm font-semibold">Metrics</h3>
        <MetricRow label="Latency (ms)"        value={data.latency_ms} />
        <MetricRow label="Latency Trend"        value={`${data.latency_trend > 0 ? '+' : ''}${data.latency_trend}`} />
        <MetricRow label="Drift Score"          value={data.drift_score.toFixed(4)} />
        <MetricRow label="Drift Status"         value={data.drift_status} />
        <MetricRow label="Traffic Processed"    value={data.traffic_processed.toLocaleString()} />
        {/* TODO: Add ECE when available in MLHealthData */}
        {/* TODO: Add Brier Score when available in MLHealthData */}
        {/* TODO: Add OOD Retention when available in MLHealthData */}
        {/* TODO: Add Failover Mode when available in MLHealthData */}
      </div>

      <ThresholdsSection thresholds={data.thresholds} />
    </div>
  )
}
