// Generated by session-9-agent — 2026-03-09T00:00:00Z
// STUB: Reports — full implementation planned for PD2
export default function ReportsPage() {
  return (
    <main className="flex flex-col gap-4">
      <h1 className="text-2xl font-semibold tracking-tight">Reports</h1>
      <div
        className="flex items-center justify-center rounded border border-dashed border-border py-24 text-muted-foreground"
        data-testid="coming-pd2"
      >
        Coming in PD2
      </div>
    </main>
  )
}
