// Generated by session-9-agent — 2026-03-09T00:00:00Z
export default function MLHealthLoading() {
  return (
    <div className="flex flex-col gap-4 animate-pulse">
      <div className="h-8 w-48 rounded bg-muted" />
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i} className="h-24 rounded bg-muted" />
        ))}
      </div>
    </div>
  )
}
