// Generated by session-9-agent — 2026-03-09T00:00:00Z
import MLHealthDetail from '@/components/ml-health/MLHealthDetail'

export default function MLHealthPage() {
  return (
    <main className="flex flex-col gap-4">
      <h1 className="text-2xl font-semibold tracking-tight">ML Health</h1>
      <MLHealthDetail />
    </main>
  )
}
