// Generated by session-9-agent — 2026-03-09T00:00:00Z
export default function AlertsLoading() {
  return (
    <div className="flex flex-col gap-4 animate-pulse">
      <div className="h-8 w-32 rounded bg-muted" />
      <div className="h-64 w-full rounded bg-muted" />
      <div className="h-48 w-full rounded bg-muted" />
    </div>
  )
}
